import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import FloatingAI from "@/components/Floatingai";

import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // sesuaikan kebutuhan
  variable: "--font-plus-jakarta", // optional: biar bisa dipakai di Tailwind
});

export const metadata: Metadata = {
  title: "Dinas Perpustakaan dan Kearsipan Daerah Provinsi Jawa Barat",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo_Dispusipda.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta.variable} ${plusJakarta.variable} antialiased`}
      >
        {children}
        <FloatingAI />
        {/* === Floating AI === */}
      </body>
    </html>
  );
}
